// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: 0002_ecommerce_users_profile.sql

package database

import (
	"context"
	"database/sql"
)

const getUserProfile = `-- name: GetUserProfile :one
SELECT first_name, last_name, phone_number, address
FROM ` + "`" + `user_profile` + "`" + `
WHERE user_id = ?
`

type GetUserProfileRow struct {
	FirstName   sql.NullString
	LastName    sql.NullString
	PhoneNumber sql.NullString
	Address     sql.NullString
}

func (q *Queries) GetUserProfile(ctx context.Context, userID string) (GetUserProfileRow, error) {
	row := q.db.QueryRowContext(ctx, getUserProfile, userID)
	var i GetUserProfileRow
	err := row.Scan(
		&i.FirstName,
		&i.LastName,
		&i.PhoneNumber,
		&i.Address,
	)
	return i, err
}

const updateUserProfile = `-- name: UpdateUserProfile :execresult
UPDATE ` + "`" + `user_profile` + "`" + `
SET
    first_name = ?,
    last_name = ?,
    phone_number = ?,
    address = ?
WHERE user_id = ?
`

type UpdateUserProfileParams struct {
	FirstName   sql.NullString
	LastName    sql.NullString
	PhoneNumber sql.NullString
	Address     sql.NullString
	UserID      string
}

func (q *Queries) UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateUserProfile,
		arg.FirstName,
		arg.LastName,
		arg.PhoneNumber,
		arg.Address,
		arg.UserID,
	)
}
