// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: 0008_ecommerce_order_items.sql

package database

import (
	"context"
	"database/sql"
)

const createOrderItem = `-- name: CreateOrderItem :execresult
INSERT INTO ` + "`" + `order_item` + "`" + `(
    order_id,
    name,
    description,
    price,
    quantity,
    image_url
)
VALUES(?, ?, ?, ?, ?, ?)
`

type CreateOrderItemParams struct {
	OrderID     int32
	Name        string
	Description sql.NullString
	Price       int64
	Quantity    int32
	ImageUrl    string
}

func (q *Queries) CreateOrderItem(ctx context.Context, arg CreateOrderItemParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createOrderItem,
		arg.OrderID,
		arg.Name,
		arg.Description,
		arg.Price,
		arg.Quantity,
		arg.ImageUrl,
	)
}
