version: '3.8'

services:
  mysql:
    image: mysql:5.7
    networks:
      - my_custom_network
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: ecommerce
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      TZ: Asia/Bangkok
    # ports:
    #   - "3306:3306"

  redis:
    image: redis:latest
    networks:
      - my_custom_network
    container_name: redis
    # ports:
    #   - "6379:6379"

  kafka:
    image: apache/kafka:latest
    networks:
      - my_custom_network
    container_name: kafka
    environment:
      KAFKA_PROCESS_ROLES: broker,controller  
      KAFKA_NODE_ID: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT  
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093  
      KAFKA_LISTENER_SECURITY_PROTOCOL: PLAINTEXT  
      KAFKA_LOG_DIRS: /var/lib/kafka/data
      KAFKA_CLUSTER_ID: 5L6g3nShT-eMCtK--X86sw
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093  
      KAFKA_LISTENER_NAME_CONTROLLER_LISTENER: CONTROLLER  
      KAFKA_LISTENERS_CONTROLLER: CONTROLLER://0.0.0.0:9093  
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER  
    # ports:
    #   - "9092:9092"   
    #   - "9093:9093"

networks:
  my_custom_network:
    name: ecommerce_network
    driver: bridge